services:

  nestjs:
    build: .
    restart: always
    command: npm run start:dev
    volumes:
      - src:/app/src
    expose:
      - "3000"
    environment:
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS_ACCESS_KEY_ID: AKIAQHMOJEPXAL56KMFZ
      AWS_SECRET_ACCESS_KEY: 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
      VIRTUAL_HOST: dev.tutelage.au
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: dev.tutelage.au
      LETSENCRYPT_EMAIL: h.t.osborne@gmail.com
    networks:
      - humus_net

volumes:
  src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./src


networks:
  humus_net:
    external: true